name: nutribaby_app
description: "Nutrisi Bayi"




publish_to: 'none' 


























version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'













dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  go_router: ^12.1.3
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.15.0
  firebase_database: ^10.3.0
  get: ^4.6.5

  # Chart
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: ^22.2.8
  #Icon
  iconsax: ^0.0.8
  ficonsax: ^0.0.3

  #Dateformatter
  intl: ^0.18.1

  provider: ^6.1.1
  #pagination
  infinite_scroll_pagination: ^4.0.0
  flutter_localization: ^0.1.7
  syncfusion_localizations: ^22.2.9
  syncfusion_flutter_datepicker: ^22.2.9
  data_table_2: ^2.5.11



  #LauncherIcon
#  flutter_launcher_icons: "^0.13.1"
  flutter_keyboard_visibility: ^6.0.0

  #MLops
#  ml_algo: ^16.17.10


















  cupertino_icons: ^1.0.2


flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/images/nutrition_background_logo.png"
  min_sdk_android: 21 # android min sdk min:16, defa

dev_dependencies:
  flutter_test:
    sdk: flutter

  

  

  

  

  

  flutter_lints: ^2.0.0







flutter:




  uses-material-design: true


  assets:
    - assets/images/
  #    - lib/features/home/data/productdata.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic


  

  

  

  


  

  


  

  


  

  

  

  

  

  

  

  

  

  

  

  

  

  

  

  

  

  

  

